### ISSUE TITLE
Stop hover option instead Click to Open sub menu

### ISSUE THREAD

**Issue by s-nadesh** [magiccart/magento-2-mega-menu#2]
Hi 

I am using this magicmenu in my magento 2 project. Instead of hover, I want to open submenu when I click parent menu. Kindly help me. 

Thank you.

**Comment by magiccart** [comment]
@s-nadesh you go to line 79 file https://github.com/magiccart/magento-2-mega-menu/blob/master/view/frontend/web/js/magicmenu.js with code below:
Replace categories.on('touchstart', function (e) {
with categories.on('touchstart click', function (e) {
Also add style below to file style
.category-item.level-top.over .level-top-mega, .category-item.level-top.over .level-top{
        display:block; 
        opacity:1;
        visibility: visible;
}
